#!/bin/sh

eval $(keychain --eval --agents gpg,ssh --quiet)
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export ZDOTDIR=$HOME/.config/zsh

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export PATH=$PATH:/sbin:/usr/sbin:$HOME/.local/bin/:$HOME/.config/composer/vendor/bin:$HOME/.local/share/go/bin

export EDITOR='nvim'
export VISUAL='nvim'

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export GOPATH=$HOME/.local/share/go
